name: 'repo size'

on: [push]

jobs:
  reposize:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch
      - uses: actions/checkout@v3
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Get repository size
      - uses: actions/checkout@v3
        run: du -skh --exclude=".git"
