name: 'repo size'

on: [push]

jobs:
  reposize:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch and Repo size
        uses: actions/checkout@v3
      - name: Get branch name
        run: echo "Branch Name = ${{ github.ref }}"
      - name: Get repository size
        run: du -skh --exclude=".git"
